### ISSUE TITLE
代码运行问题——关于myutils包

### ISSUE THREAD

**Issue by zhoushijie28** [cool-xuan/AnoOnly#1]
您好，最近学习了您的这篇文章，在您公布的代码中引用了myutils包中的Utils，但是在通过pip install myutils命令安装后，myutlis.py文件中并没有Utils函数，因此在运行代码时会报错：ImportError: cannot import name 'Utils' from 'myutils' (D:\anaconda\anaconda\envs\pytorch\lib\site-packages\myutils.py)，不知道是否时myutils包的问题，希望得到您的解答，谢谢！

**Comment by cool-xuan** [comment]
Thanks for your admiration of our work. I have missed `myutils.py' in our first code submission, and this file have been uploaded to the github. Please try it again.
